modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "MIT"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"


[[mods]] #mandatory
modId = "compactmachines"
version = "${mod_version}"
displayName = "Compact Machines 6"
authors = "Davenonymous, RobotGryphon" #optional
description = "It's all so tiny!"
featureFlags="META-INF/feature_flags.json"

issueTrackerURL = "https://github.com/CompactMods/CompactMachines/issues"

#updateJSONURL="http://myurl.me/" #optional
displayURL = "https://compactmods.dev"

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.compactmachines]] #optional
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.compactmachines]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"