[versions.feather]
require = "0.1.8"

[versions.spatial]
require = "[0.2.0, 0.3)"
prefer = "0.2.1"

[libraries.feather]
module = "dev.compactmods:feather"
version.ref = "feather"

[libraries.spatial]
module = "dev.compactmods:spatial"
version.ref = "spatial"
