name: Announce Latest Nightly Build to Discord
env:
  GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
  workflow_dispatch:

jobs:
  get-package-info:
    name: Latest Package Info
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.download-info.outputs.version }}
    steps:
      - name: Download Package Info
        id: download-info
        uses: compactmods/dl-package-info@1.0.3
        env:
          GQL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: compactmods
          repo: compactmachines
          group: dev.compactmods.compactmachines.compactmachines-neoforge
          filter: "^compactmachines-neoforge-(?:[\\d\\.]+).jar$"
          outputFile: compactmachines.json

      - name: Debug output
        run: |
          echo "Version: ${{ steps.download-info.outputs.version }}"
          cat compactmachines.json

  announce:
    name: Discord Announcement
    uses: _announce-latest-build.yml
    secrets: inherit