name: Publish and Announce Nightly Build

env:
  GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: Skip Tests
        type: boolean
        default: false
        required: true
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/**/*"
      - "**/*.gradle.kts"
      - "**/gradle.properties"

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-22.04
    outputs:
      version: ${{steps.version.outputs.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 150
          fetch-tags: true

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "neoforge-main"
          version_format: "${major}.${minor}.${patch}.${increment}-nightly"
          search_commit_body: true
          bump_each_commit: true

  datagen:
    needs: [vars]
    uses: ./.github/workflows/_datagen.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  tests:
    if: ${{ !inputs.skip_tests }}
    needs: [vars, datagen]
    uses: ./.github/workflows/_run-gametests.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  publish-after-tests:
    needs: [vars, tests]
    if: ${{ !inputs.skip_tests && needs.tests.result == 'success' }}
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  publish-after-no-tests:
    needs: [vars, datagen]
    if: ${{ inputs.skip_tests && needs.datagen.result == 'success' }}
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  after-publish:
    runs-on: ubuntu-latest
    needs: [publish-after-tests, publish-after-no-tests]
    if: ${{ always() }}
    steps:
      - name: no-op
        run: echo ""

  announce:
    name: Discord Announcement
    needs: [ after-publish ]
    if: ${{ always() }}
    uses: ./.github/workflows/_announce-latest-nightly.yml
    secrets: inherit