name: Run Game Tests

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  run-tests:
      name: Run Game Testss
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Pull Built Generated Data
          uses: actions/download-artifact@v4
          with:
            name: generated-data
            path: neoforge-main/src/generated/resources

        - name: Run Game Tests
          run: ./gradlew :neoforge-main:test
          env:
            VERSION: ${{ inputs.version }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload build failure
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: test-data
            path: run/gametest